### PR TITLE
add unknown occupancy

### PR DESCRIPTION
**Pull request by Haroenv**
This was there before #237 

related to #247

### CODE REVIEW

**Comment by Haroenv** [comment]
Accidentally proposed to master instead of develop

**Comment by Tjoosten** [comment]
If you click edit you can also change the branch :3

**Comment by Haroenv** [comment]
TIL, thanks

**Comment by Tjoosten** [comment]
TIL?

**Comment by Haroenv** [comment]
[Today I Learned](https://www.reddit.com/r/todayilearned/)

**Comment by Tjoosten** [comment]
Thx

**Pull request closed without merging**
