### PR TITLE
Feature/design tweaks

### LINKED ISSUE #186: Why are there two Sass source folders?
Why is there a `sass` folder here: https://github.com/iRail/hyperRail/tree/master/resources/assets/sass and here: https://github.com/iRail/hyperRail/tree/master/public/app/sass ?

### PR DESCRIPTION
**Pull request by xavez**
This PR contains

- A new design for the homepage
- Restructured `scss` files
- Swapped some custom css for default bootstrap css
- Removed a bunch of unnecessary css (see `main.scss`)
- Improved Grunt workflow

## New homepage design

- A lot of tiny accessibility improvements like fast keyboard use and proper linking of labels to inputs
- Removed confusing live-board button inside input fields. People should use the "find station" button.
- Simplified depart / arrive settings for people who just want to leave now
- Bigger touch targets for autocomplete forms

This PR also fixes #186 #169

### CODE REVIEW

**Comment by pietercolpaert** [comment]
Thanks @xavez! The iRail main page certainly looks way more beautiful now!

**Comment by xavez** [comment]
@pietercolpaert seems like the CSS / JS didn’t regenerate though?

**Comment by pietercolpaert** [comment]
Hmmm... Anything I could have forgotten? Aren't the build files added in the repo anymore?

**Comment by xavez** [comment]
They still are . . . maybe run the grunt task manually?

**Comment by pietercolpaert** [comment]
Fixed: was cache error

**Pull request merged**
