### PR TITLE
Shiplist for PR #141

### PR DESCRIPTION
**Pull request by Tjoosten**
# Shiplist for PR #141. 

## Misc. changes.

- eb3f27b Sync `Tjoosten:development` with `iRail:development`. 

## Changes *(`.md` files)*.

- e729a1a Added [CC0](https://creativecommons.org/about/cc0) license label on the `readme.md`.
- 5803058 Added NodeJS dependency label on the `readme.md`
- 64ba262 Added NodeJS dev dependency label on the `readme.md`. - **FIX:** b7b7952
- 4bbd77b Rewrite `contribution.md`.

## Changes code *(PHP)*.
- b9f5e4a Replace old `View::make` and replace it with `View()`
- c02a857 Improve docblock in `routes.php`.
- 714e42a Update second docblock in `routes.php`.
- ba1a840 Remove unused `use` statements.
- 4f5cdc3  Change `array()` to `[]`.
- 330f941 Bringing `app/hyperrail/StationString.php` back into the project. **FIXING:** [this issue](https://irail.be/board/turnhout).
- c0c7698 Add Guzzle to `composer.json`. **Preparation for:** #15;
  - convert to `GuzzleHTTP` on a couple functions. - dd1251c
- 91873ee Added missing view. *`(station/departurearchieve.blade.php)`*
- d378040 Added missing view. *`(station/departuredetail.blade.pgp)`*

## Changes code *(JS)*.
- be35e49 Remove unneeded comma's.

## Testing.
- 1943307 Add [TravisCI](http://travisci.org) configuration file.
- 7fdfeb1 Add PHPunit test for `/station/NMBS/{id}`.
  - Add PHPunit test for the lowercased variant. - d11b2ae
- 1611952 Add PHPunit test for `/station/NMBS/{id}/departures`.
   - Add PHPunit test for the lowercased variant. - bc5f10b
- b34c361 Added unit test for the route `/board/{station1}/{station2}`.

## TODO in next PR.

- Add TravisCI build label. - Waiting till Pieter make the configuration in travis.
- Investigate & test the namespace changes that the StyleCI make.

## Notes 
- **[23/08/2015 - 02:26H]:** Still working on this one.
- **[23/08/2015 - 03:28H]:** Im sleepless so i contribute to this project. "kudos to me"
- **[23/08/2015 - 03:36H]:** Brace for impact! More commits for this PR tomorrow. Don't merge it plz.
- **[23/08/2012 - 18:09H]:** I'm done. @pietercolpaert you can merge this if you want.

### CODE REVIEW

**Comment by pietercolpaert** [comment]
Regarding https://github.com/iRail/hyperRail/commit/330f9412f4b826808aa38a28235e5bc332241216: I overlooked the fact that that class was still used there. The solution however is not to bring back this old code, but by using `irail\stations\Stations::getStations($name)` to resolve a station's name.

**Comment by Tjoosten** [comment]
330f941: is just a quick and dirty fix Pieter. But i agree this needs a better solution.

**Comment by pietercolpaert** [comment]
Indeed... we should add `/stations/sncb/008727100` it to the project in my opinion... Just for completeness sake :)

**Comment by Tjoosten** [comment]
@pietercolpaert have seen the guzzle implementation commit. I'm not sure about that commit. 

And can u explain more about that `/stations/sncb/00872100` implementation. Maybe i can work out something?

**Pull request merged**
