### PR TITLE
Development

### PR DESCRIPTION
**Pull request by pietercolpaert**
- Using SVG icons instead
- Feedback enabled 5 minutes before departure instead
- Removed copyright
- Fixed URI of stations on feedback
- Fixed size of form control on iOS
- More translations

### CODE REVIEW

**Comment by pietercolpaert** [comment]
@Haroenv now on desktop the font is also smaller... Is this better you believe?

Somehow right now, when I test this, I cannot get the form to work: it doesn't give a result. Anyone any idea why this happens? I don't get any javascript console errors

**Comment by Haroenv** [comment]
The font should be larger than before, maybe I made a mistake ... @pietercolpaert

**Comment by Haroenv** [comment]
I found the issue that stops the route from displaying: @SerkanYildiz' `getApiResponse` doesn't work for me, it's fixed by changing that back to `file_get_contents` (which is slower though...)

**Comment by Haroenv** [comment]
`.form-control` is now 16px at all times for me, it used to be 14.

**Comment by pietercolpaert** [comment]
Don' tknow what's happening now, but now in many cases the feedback form is not showing any longer... @SerkanYildiz @Haroenv

**Comment by Haroenv** [comment]
You're right, in `development` now, the feedback form shows 30 minutes earlier than it's supposed to. It's 13:08 and I see the form on 12:32 - 12:57

**Comment by pietercolpaert** [comment]
I'd also like to submit occupancy levels about a train I took this morning, or even yesterday. I'm in favour of having the window unlimited in the past and have it stop 5 minutes in the future.

**Comment by Haroenv** [comment]
Inclined to agree with you for that. The formula now is a bit complicated, and just showing it when it's not 5 minutes in the future should be fine

**Comment by Haroenv** [comment]
👍

**Pull request merged**
