### PR TITLE
Show feedback 5 minutes before departure

### PR DESCRIPTION
**Pull request by SerkanYildiz**
Showing feedback form 5 minutes before departure. I need to add a condition that it will be shown 15 minutes (more or less?) after arrival time. 
This is for issue #217 
DO NOT MERGE THIS.

### CODE REVIEW

**Comment by pietercolpaert** [comment]
@SerkanYildiz Any roadmap for this PR?

**Comment by SerkanYildiz** [comment]
Will finish this tomorrow.

**Comment by SerkanYildiz** [comment]
Fixed, this can be merged now. @pietercolpaert

**Comment by pietercolpaert** [comment]
Thanks @SerkanYildiz!

**Pull request merged**
