### PR TITLE
also change formula on another location

### PR DESCRIPTION
**Pull request by Haroenv**
However I noticed that it now shows all the time. 

See #239

### CODE REVIEW

**Comment by Haroenv** [comment]
EDIT: it already works like advertised. Shows up to 10 minutes in the future @pietercolpaert (I was just testing on a "earlier" page, so all of them were visible and I didn't noticed that that was correct.

**Comment by Haroenv** [comment]
Also useful to figure out why that is verbatim visible twice. It should probably be exported into a partial.

**Comment by pietercolpaert** [comment]
Thanks! Seems to work like a charm now! Will put in production later this week when I find some time!

**Comment by Haroenv** [comment]
super!

**Pull request merged**
