### PR TITLE
Applied fixes from StyleCI

### PR DESCRIPTION
**Pull request by pietercolpaert**
This pull request applies code style fixes from an analysis carried out by [StyleCI](https://styleci.io).

---

For more information, click [here](https://styleci.io/analyses/8jj3G8).

### CODE REVIEW

**Comment by pietercolpaert** [comment]
@Tjoosten What do you think? Merge it?

**Comment by Tjoosten** [comment]
I should merge it. But i'm worried about the change in the namespaces. If that is no problem then merge it.

**Comment by pietercolpaert** [comment]
Good point...

**Comment by Tjoosten** [comment]
i don't know. But on that fact worried. I think the best is that we test this out before merge. To avoid some possible nasty errors.

**Pull request closed without merging**
