### PR TITLE
Update to Laravel 5.1

### PR DESCRIPTION
**Pull request by pietercolpaert**
This pull request updates the laravel version from 4.0 to 5.1

### CODE REVIEW

**Comment by nicoverbruggen** [comment]
Just fired it up locally. Looks good to me. I do have two remarks I'd like someone to verify:

* Collapse/expand of route results doesn't work on my local install (this might be a local issue)
* Also getting a `Uncaught TypeError: $(...).tooltip is not a function` on `route:264`

I don't have time to investigate this further. @pietercolpaert: If you can't reproduce those issues, feel free to merge this PR. If not, well, we'll have to make issues for them here on GitHub.

**Comment by Tjoosten** [comment]
@pietercolpaert @nicoverbruggen plz wait before merge this one i noticed some missing things like favicon, apple icon. etc... I will bring this back in ASAP

**Comment by pietercolpaert** [comment]
@Tjoosten does the collapse/expand work for you? Works for me here...

**Comment by Tjoosten** [comment]
Here it works. But that `Uncaught TypeError: $(...).tooltip is not a function` on `route:264`
needs investigation in my opinion

**Comment by nicoverbruggen** [comment]
screen shot 2015-08-19 at 17 10 59

This is from the live version. Does this tooltip appear? I'm guessing it's this.

**Comment by Tjoosten** [comment]
It doesn't appear by me @nicoverbruggen

**Comment by pietercolpaert** [comment]
I merged this with development now. Will open a different PR for development to stable master soon

**Comment by Tjoosten** [comment]
Alright I'm making in that time further improvements.

**Pull request closed without merging**
