### PR TITLE
Update to l5.1

### PR DESCRIPTION
**Pull request by Tjoosten**

### CODE REVIEW

**Comment by pietercolpaert** [comment]
Your README.md is now overwritten by the readme.md of laravel. Can you make sure README.md remains the iRail one?

Furthermore: why do we have a database and email configuration? We don't use a database or e-mail, right?

**Comment by Tjoosten** [comment]
do you mean the .env? and yes. I told you yesterday that this isn't ready for production. The small things i needed to migrated are planned for tonight or tomorrow.

**Comment by Tjoosten** [comment]
@pietercolpaert added the readme but it still needs to be edited

**Comment by Tjoosten** [comment]
I got an issue with the gulp parser.
schermafbeelding 2015-08-18 om 17 04 16

it would be fun if i get some help with this one.

**Pull request merged**
