### PR TITLE
Merge pull request #15 from iRail/development

### PR DESCRIPTION
**Pull request by Tjoosten**
Merge pull request #160 from Tjoosten/development

Changes 

- StyleCI fixes
- Add codecov
- Add documentatie comments to the travisci file.
- Ads PHPunit test for `redirectSettings()` -> ClassicRedirectController.php
- Add PHPunit test for `convertToId()` -> StationString.php.
- Add PHPunit test for `convertToString` -> StationString.php
- Improve index routes Unit test. -> Affects coverage

### CODE REVIEW

**Comment by Tjoosten** [comment]
@pietercolpaert merge plz

**Comment by pietercolpaert** [comment]
Won't merge if tests fail (obviously)

Other than that: these commit messages are hideous. Please rebase into better 1 or more commit(s) that will show the history better when merged. You can find a how-to on rebasing here:
 * https://www.atlassian.com/git/tutorials/rewriting-history
 * http://rypress.com/tutorials/git/rebasing

**Comment by pietercolpaert** [comment]
Checking out the PR, I saw you also committed storage files: remove these from your commits please.

**Comment by Tjoosten** [comment]
Rabasing keeps failing.

**Comment by pietercolpaert** [comment]
StyleCI still fails. I'm not sure what this pull request adds to hyperRail. Open a new pull request with clearer commit messages if you still would like to see this merged

**Comment by Tjoosten** [comment]
Maybe

**Pull request closed without merging**
