### PR TITLE
Set language from browser, accept enter key in planner #242 #243

### PR DESCRIPTION
**Pull request by Bertware**
Resolves issues #242 and #243.
Note: 
\Locale::lookup is a php function from the php_intl module. The page won't show if this module is not available.

### CODE REVIEW

**Comment by Haroenv** [comment]
Tests will need to change I guess (as well as linting errors)

**Comment by pietercolpaert** [comment]
Looks good indeed! Can you fix the test as well?

**Comment by pietercolpaert** [comment]
This probably means we can finally get rid of the cookies as well, right?

**Comment by Bertware** [comment]
While fixing the tests, I also added some new tests, to ensure that special cases are handled correctly. The language detection has been changed, instead of locale_lookup we're now using our own method. This was needed to support headers like "da, nl;q=0.9, en;q=0.2", where danish is not supported but Dutch and English are. While locale_lookup would fail, our own method will select nl in this case.

About the cookies: since users can still override the language, the cookies are still used.

**Comment by Bertware** [comment]
Cookies will have to stay required. When using a device frome someone else with a different browser language, users should still be able to pick their language (looking up trains while at a friend, for example). However, maybe we can keep all cookie code in the language middleware, including the pick language redirect (this redirect is currently still located in the home controller).

Also note that cookies to remember a language are allowed in the updated cookie law. (since widely used for user expierience, and not used for tracking)

**Pull request merged**
