### PR TITLE
Getting connections with cURL iso file_get_contents.

### PR DESCRIPTION
**Pull request by SerkanYildiz**
cURL is much faster than file_get_contents.

### CODE REVIEW

**Comment by pietercolpaert** [comment]
Thanks Serkan!

**Comment by xavez** [comment]
Nice. Not sure if I'm dreaming but it actually feels faster!

**Comment by pietercolpaert** [comment]
Dreaming ;) it's in development, not yet in production

Op zo 14 aug. 2016 07:53 schreef Xavier Bertels <notifications@github.com>:

**Comment by xavez** [comment]
Well, perception is everything 📦 .

**Pull request merged**
